version: '3.8'
services:
  jenkins:
    # image: jenkins/jenkins:lts-jdk17   -> chanage to docker file which install docker cli
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - '8000:8080'
      # - "50000:50000" if system is distributed
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Seoul
